/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PatientManagementSystem;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lee
 */
public class PatientManagementSystem extends javax.swing.JFrame {
    private JFrame frame;

    /**
     * Creates new form PatientManagementSystem
     */
    public PatientManagementSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPrescription = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButtonPrescribe = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxMedicationName = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextSex = new javax.swing.JTextField();
        jTextDoctorName = new javax.swing.JTextField();
        jTextDoctorAddress = new javax.swing.JTextField();
        jTextQuantity = new javax.swing.JTextField();
        jTextReccomendedDose = new javax.swing.JTextField();
        jTextPatientName = new javax.swing.JTextField();
        jTextPatientAddress = new javax.swing.JTextField();
        jComboBoxDoctorID = new javax.swing.JComboBox<>();
        jTextAge = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextDosage = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextNotes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(418, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(411, 411, 411))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1370, 90));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTextPrescription.setBackground(new java.awt.Color(255, 255, 255));
        jTextPrescription.setColumns(20);
        jTextPrescription.setForeground(new java.awt.Color(0, 0, 0));
        jTextPrescription.setRows(5);
        jScrollPane1.setViewportView(jTextPrescription);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 120, 390, 540));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setBackground(new java.awt.Color(240, 240, 240));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Doctor - Patient pescription");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(199, 199, 199))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 980, 80));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jButton1.setText("Save");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Appointment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Buttons");

        jButton4.setText("Patient");

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Login");

        jButton7.setText("Exit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButtonPrescribe.setText("Prescribe");
        jButtonPrescribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrescribeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButtonPrescribe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(50, 50, 50)
                .addComponent(jButton4)
                .addGap(29, 29, 29)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButtonPrescribe)
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(10, 10, 10))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, 460));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Doctor Address :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, 30));

        jComboBoxMedicationName.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxMedicationName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBoxMedicationName.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxMedicationName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Medication", "Aspirin", "Paracetamol", "Co-codamal", "Rampril", "Mega Paracetamol", "Caffiene", "Burn Cream", "ibuprofen", "Zopiclone", "Loratadine" }));
        jComboBoxMedicationName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMedicationNameActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxMedicationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Medication Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Quantity :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, -1, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Reccomended dose :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 190, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Notes :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, -1, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Doctor Name :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Doctor ID :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Patient Name :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Patient Address :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Sex :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, -1, 30));

        jTextSex.setBackground(new java.awt.Color(255, 255, 255));
        jTextSex.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextSex.setForeground(new java.awt.Color(0, 0, 0));
        jTextSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSexActionPerformed(evt);
            }
        });
        getContentPane().add(jTextSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 100, -1));

        jTextDoctorName.setBackground(new java.awt.Color(255, 255, 255));
        jTextDoctorName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextDoctorName.setForeground(new java.awt.Color(0, 0, 0));
        jTextDoctorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDoctorNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextDoctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 200, -1));

        jTextDoctorAddress.setBackground(new java.awt.Color(255, 255, 255));
        jTextDoctorAddress.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextDoctorAddress.setForeground(new java.awt.Color(0, 0, 0));
        jTextDoctorAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDoctorAddressActionPerformed(evt);
            }
        });
        getContentPane().add(jTextDoctorAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 200, -1));

        jTextQuantity.setBackground(new java.awt.Color(255, 255, 255));
        jTextQuantity.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextQuantity.setForeground(new java.awt.Color(0, 0, 0));
        jTextQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQuantityActionPerformed(evt);
            }
        });
        getContentPane().add(jTextQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 80, -1));

        jTextReccomendedDose.setBackground(new java.awt.Color(255, 255, 255));
        jTextReccomendedDose.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextReccomendedDose.setForeground(new java.awt.Color(0, 0, 0));
        jTextReccomendedDose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextReccomendedDoseActionPerformed(evt);
            }
        });
        getContentPane().add(jTextReccomendedDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 260, -1));

        jTextPatientName.setBackground(new java.awt.Color(255, 255, 255));
        jTextPatientName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextPatientName.setForeground(new java.awt.Color(0, 0, 0));
        jTextPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPatientNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 260, -1));

        jTextPatientAddress.setBackground(new java.awt.Color(255, 255, 255));
        jTextPatientAddress.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextPatientAddress.setForeground(new java.awt.Color(0, 0, 0));
        jTextPatientAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPatientAddressActionPerformed(evt);
            }
        });
        getContentPane().add(jTextPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 260, -1));

        jComboBoxDoctorID.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxDoctorID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBoxDoctorID.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxDoctorID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ID", "D9911", "D9922", "D9933" }));
        jComboBoxDoctorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDoctorIDActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDoctorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 150, -1));

        jTextAge.setBackground(new java.awt.Color(255, 255, 255));
        jTextAge.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextAge.setForeground(new java.awt.Color(0, 0, 0));
        jTextAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAgeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 70, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Age :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Dosage (mg) :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, 30));

        jTextDosage.setBackground(new java.awt.Color(255, 255, 255));
        jTextDosage.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextDosage.setForeground(new java.awt.Color(0, 0, 0));
        jTextDosage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDosageActionPerformed(evt);
            }
        });
        getContentPane().add(jTextDosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 200, -1));
        jTextDosage.getAccessibleContext().setAccessibleName("");
        jTextDosage.getAccessibleContext().setAccessibleDescription("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor ID", "Doctor Name", "Doctor Address", "Medication Name", "Dosage (mg)", "Quantity", "Reccomended dose", "Patient Name", "Patient Address", "Sex", "Age", "Notes"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 1360, 180));

        jTextNotes.setBackground(new java.awt.Color(255, 255, 255));
        jTextNotes.setColumns(20);
        jTextNotes.setRows(5);
        jScrollPane3.setViewportView(jTextNotes);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 350, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMedicationNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMedicationNameActionPerformed
       if (jComboBoxMedicationName.getSelectedItem().equals("Aspirin")) 
       {
           jTextQuantity.setText("62");
           jTextDosage.setText("45");
           jTextReccomendedDose.setText("2 tablets once a day");
           
           
       }
       
       else if (jComboBoxMedicationName.getSelectedItem().equals("Paracetamol"))
           
       {
           jTextQuantity.setText("42");
           jTextDosage.setText("600");
           jTextReccomendedDose.setText("1 tablet twice a day");
           
           
       }
       
       else if (jComboBoxMedicationName.getSelectedItem().equals("Co-codamal"))
           
       {
           jTextQuantity.setText("100");
           jTextDosage.setText("150");
           jTextReccomendedDose.setText("2 tablets twice a day");
           
           
       }
       
       else if (jComboBoxMedicationName.getSelectedItem().equals("Rampril"))
           
       {
           jTextQuantity.setText("26");
           jTextDosage.setText("6");
           jTextReccomendedDose.setText("1 tablet once a day");
           
           
       }
       
       else if (jComboBoxMedicationName.getSelectedItem().equals("Mega Paracetamol"))
           
       {
           jTextQuantity.setText("30");
           jTextDosage.setText("1000");
           jTextReccomendedDose.setText("1 tablet twice a day");
           
           
       }
       
       else if (jComboBoxMedicationName.getSelectedItem().equals("Caffiene"))
           
       {
           jTextQuantity.setText("300");
           jTextDosage.setText("100");
           jTextReccomendedDose.setText("1 tablet three times a day");
           
           
       }
       
       else if (jComboBoxMedicationName.getSelectedItem().equals("Burn Cream"))
           
       {
           jTextQuantity.setText("1");
           jTextDosage.setText("1500");
           jTextReccomendedDose.setText("Apply once a day");
           
           
       }
       
       
         else if (jComboBoxMedicationName.getSelectedItem().equals("ibuprofen"))
           
       {
           jTextQuantity.setText("70");
           jTextDosage.setText("180");
           jTextReccomendedDose.setText("1 tablet four times a day");
           
       }
       
        else if (jComboBoxMedicationName.getSelectedItem().equals("Zopiclone"))
           
       {
           jTextQuantity.setText("25");
           jTextDosage.setText("80");
           jTextReccomendedDose.setText("1 tablet before bed");
           
       }
       
           else if (jComboBoxMedicationName.getSelectedItem().equals("Loratadine"))
           
       {
           jTextQuantity.setText("60");
           jTextDosage.setText("15");
           jTextReccomendedDose.setText("1 tablet in morning");
           
       }
       
         else if (jComboBoxMedicationName.getSelectedItem().equals("Select Medication"))
           
       {
           jTextQuantity.setText("");
           jTextDosage.setText("");
           jTextReccomendedDose.setText("");
           
       }
       
  
       
    }//GEN-LAST:event_jComboBoxMedicationNameActionPerformed

    private void jTextSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSexActionPerformed

    private void jTextDoctorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDoctorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDoctorNameActionPerformed

    private void jTextDoctorAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDoctorAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDoctorAddressActionPerformed

    private void jTextQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQuantityActionPerformed

    private void jTextReccomendedDoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextReccomendedDoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextReccomendedDoseActionPerformed

    private void jTextPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPatientNameActionPerformed

    private void jTextPatientAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPatientAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPatientAddressActionPerformed

    private void jTextAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAgeActionPerformed

    private void jTextDosageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDosageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDosageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        frame =new JFrame();
        if (JOptionPane.showConfirmDialog(frame,"Do you want to exit?", "Patient Management System",
              JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
             System.exit(0);
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonPrescribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrescribeActionPerformed
       
        String Quantity1 = (jTextPatientName.getText());
        String Quantity2 = (jTextPatientAddress.getText());
        String Quantity3 = (jTextSex.getText());
        String Quantity4 = (jTextAge.getText());
        String Quantity5 = (jTextDosage.getText());
        String Quantity6 = (jTextQuantity.getText());
        String Quantity7 = (jTextReccomendedDose.getText());
        String Quantity8 = (jTextDoctorName.getText());
        String Quantity9 = (jTextDoctorAddress.getText());
        String Quantity10 = (jTextNotes.getText());
        String Quantity11 = "";
        
        
        
        
        
        if (jComboBoxMedicationName.getSelectedItem().equals("Aspirin"))
        {
            
            Quantity11 = "Aspirin";
        }
        
        else if (jComboBoxMedicationName.getSelectedItem().equals("Paracetamol"))
        {
            
            Quantity11 = "Paracetamol";
            
        }
        
        else if (jComboBoxMedicationName.getSelectedItem().equals("Co-codamal"))
        {
            
            Quantity11 = "Co-codamal";
            
        }
        
        else if (jComboBoxMedicationName.getSelectedItem().equals("Rampril"))
        {
            
            Quantity11 = "Rampril";
            
        }
        else if (jComboBoxMedicationName.getSelectedItem().equals("Mega Paracetamol"))
        {
            
            Quantity11 = "Mega Paracetamol";
            
        }
        else if (jComboBoxMedicationName.getSelectedItem().equals("Caffiene"))
        {
            
            Quantity11 = "Caffiene";
            
        }
        else if (jComboBoxMedicationName.getSelectedItem().equals("Burn Cream"))
        {
            
            Quantity11 = "Burn Cream";
            
        }
        else if (jComboBoxMedicationName.getSelectedItem().equals("ibuprofen"))
        {
            
            Quantity11 = "ibuprofen";
            
        }
        else if (jComboBoxMedicationName.getSelectedItem().equals("Zopiclone"))
        {
            
            Quantity11 = "Zopiclone";
            
        }
        else if (jComboBoxMedicationName.getSelectedItem().equals("Loratadine"))
        {
            
            Quantity11 = "Loratadine";
            
        }
        
        
        jTextPrescription.setText("");
        jTextPrescription.append("\t\n\tPrescription Details\n"
                +"\nPatient Name:\t\t" + Quantity1
                +"\nPatient Address:\t" + Quantity2
                +"\nPatient Sex:\t\t" + Quantity3
                +"\nPatient Age:\t\t" + Quantity4
                +"\n\nMedication:\t\t" + Quantity11
                +"\nDosage:\t\t" + Quantity5
                +"\nQuantity:\t\t" + Quantity6
                +"\nReccomendedDose:\t" + Quantity7
                +"\n\nDoctors Name:\t\t" + Quantity8
                +"\nDoctors Address:\t" + Quantity9
                +"\n\n\tDoctors Notes\n\t" + Quantity10
          
        );
  
        
        
        
    }//GEN-LAST:event_jButtonPrescribeActionPerformed

    private void jComboBoxDoctorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDoctorIDActionPerformed
      if (jComboBoxDoctorID.getSelectedItem().equals("D9911")) 
       {
           jTextDoctorName.setText("Dr Mark Ruffalo");
           jTextDoctorAddress.setText("123 Good Clinic");
           
           
           
       }
       
       else if (jComboBoxDoctorID.getSelectedItem().equals("D9922"))
           
       {
           jTextDoctorName.setText("Dr Stephen Strange");
           jTextDoctorAddress.setText("123 Good Clinic");
           
           
       }
      
        else if (jComboBoxDoctorID.getSelectedItem().equals("D9933"))
           
       {
           jTextDoctorName.setText("Dr Walter White");
           jTextDoctorAddress.setText("123 Good Clinic");
           
           
       }
      
      else if (jComboBoxDoctorID.getSelectedItem().equals("Select ID"))
           
       {
           jTextDoctorName.setText("");
           jTextDoctorAddress.setText("");
           
           
       }
    }//GEN-LAST:event_jComboBoxDoctorIDActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       jTextQuantity.setText("");
       jTextDosage.setText("");
       jTextReccomendedDose.setText("");
       jTextPatientAddress.setText("");
       jTextSex.setText("");
       jTextAge.setText("");
       jTextDoctorName.setText("");
       jTextDoctorAddress.setText("");
       jTextNotes.setText("");
       jTextPatientName.setText("");
       jTextPrescription.setText("");
       jComboBoxMedicationName.getModel().setSelectedItem("Select Medication");
       jComboBoxDoctorID.getModel().setSelectedItem("Doctor ID");
       
       
  
       
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientManagementSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonPrescribe;
    private javax.swing.JComboBox<String> jComboBoxDoctorID;
    private javax.swing.JComboBox<String> jComboBoxMedicationName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextAge;
    private javax.swing.JTextField jTextDoctorAddress;
    private javax.swing.JTextField jTextDoctorName;
    private javax.swing.JTextField jTextDosage;
    private javax.swing.JTextArea jTextNotes;
    private javax.swing.JTextField jTextPatientAddress;
    private javax.swing.JTextField jTextPatientName;
    private javax.swing.JTextArea jTextPrescription;
    private javax.swing.JTextField jTextQuantity;
    private javax.swing.JTextField jTextReccomendedDose;
    private javax.swing.JTextField jTextSex;
    // End of variables declaration//GEN-END:variables
}
